### PR TITLE
New Website

### LINKED ISSUE #81: Update the website
I think this repo is cool and more people should know it.
I was thinking of contributing by updating the website for this repo so that people can find it on search engines.
I was think of using [docsify ](https://docsify.js.org/)and I think it will look great.

### PR DESCRIPTION
**Pull request by Bashamega**
image
closes #81

### CODE REVIEW

**Comment by phodal** [comment]
@Bashamega  Can you also add how to build ? or build script

**Comment by Bashamega** [comment]
> @Bashamega Can you also add how to build ? or build script

Just run the python script this is for just add the md to the sidebar. if you won't add new tutorials you don't need to run it.
If you want just run it with python.

**Comment by phodal** [comment]
@Bashamega But, if we update content, we need to rebuild it ??

**Comment by Bashamega** [comment]
> @Bashamega But, if we update content, we need to rebuild it ??

Yes. Or just add the new item manually to the `_sidebar.md` file

**Pull request merged**
